language: python
python:
    - 3.3
    - 3.4
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq inotify-tools
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
    - python bootstrap.py
    - bin/buildout
    - bin/serve > temp & inotifywait temp
script:
    - bin/test
notifications:
    email: false
